[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup.astro"
  status = 200

[context.production.environment]
  SUPABASE_URL = "https://wwbzcktileifymrgvdos.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Ynpja3RpbGVpZnltcmd2ZG9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3NTY5MzgsImV4cCI6MjA0ODMzMjkzOH0.QQLOTF0Q0pdb1k36Voargou9CqX0smbEgedOrxWvtbw"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/entry/:splat"
  status = 200